# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(upload_to='media/profilephotos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePhotos',
            field=models.ImageField(upload_to='media/profilePhotos/'),
        ),
    ]
