# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-19 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190318_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_picture',
        ),
    ]
