# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-20 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_post_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_picture',
        ),
    ]
